{% set version = "0.1.1" %}

package:
  name: mkdocs-bootstrap
  version: {{ version }}

source:
  fn: mkdocs-bootstrap-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/mkdocs-bootstrap/mkdocs-bootstrap-{{ version }}.tar.gz
  sha256: 15084a6be59393fe5ecb9f04d09e674337a69fbd1e6ec5d9328e606a6c6cab36

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - mkdocs_bootstrap

about:
  home: http://www.mkdocs.org
  license: BSD 2-Clause
  summary: 'Bootstrap theme for MkDocs'

extra:
  recipe-maintainers:
    - ocefpaf
