travis:
  secure:
    BINSTAR_TOKEN: P6IeHptxS3R2/iUC960KSxL+X15W9FPxJKfGNrUwtK0VIeKt4vmN1ClBknHTrA3mAYEAri+9lAbPpGvEtI/hfZNWJ55KRpTUMpmoKwoRwFFC8oXwm5E97jLs5fF/lO0qzreh4LJu9o86RAFpqBXD564sTdXuXzjyh0nmjzPPLCBuEccxeFLhVkxOx4zHUqpbYQNfEy+orltOjcaqKFvGNlepFV9hjJ/OeyGaRu7IfeFeXTjwxtZJibl8tmviflDnBpcTG8M2kQdOym2N1vmyKYShJL5vqBk5CpcGqig0vhEVUWB/5+EAxoGtvG8uBBo/ywowMOG27lfZkzS886K8YNJaxFT6g2A7FDH5NlUVAGAiSdZzLvB/PUepMEVlxEQINRyzUkMWusV9EK7yewO8vIxkY3RAeiYTNEi1LUHgHBGDcOrVWM7iGVws0t8iyipkuPMh2zs0BWUYwALv5WuVn00p7+UIF1WNAijxtpcCsvg2guvamPllGCtQ9CByDkr1Rrda9Le8Ckd6sKa5jl3Gzrx9rLSfgUrDe3X25bPQ/l7kucijW7a7SVA9ZnJPj4aAAHvDJ0OleMGYZdj560HuK1gr3yqe6NoD7UCv5TeLFl/yMK+FpVMtmuj1PL7W+r5dl5lRU7e1pSBnmE0TuvFsHn7ejWU6r0nWYbHaZiEavWA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
